name: CI
on: [pull_request, workflow_dispatch]

jobs:
  unit_tests:
    name: Unit tests (Python)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt
    - name: Run Python unit tests
      run: |
        python -m pytest utest
